"""Offline decision-tree generator (Option 1, single-pass) — offline_tree_generator_spec.

Drives the REAL engine in `deterministic` selection mode at the shipped config
(misconception_conditional_extra = 0), walking BOTH answer outcomes at every node,
deduplicating on the single-pass state key (5.3), bounded at the grade budget.
The tree is generated by the engine production runs, never a reimplementation (5.1).

Checkpoint 1 builds one grade and reports: node/leaf count, serialized size,
the determinism check (5.5), the merge soundness check (do paths that merge on the
single-pass key carry identical misconception counts?), and the posterior-bucketing
sensitivity probe (open point 1).
"""
from __future__ import annotations
import os
import copy, json, sys, hashlib, time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

ENGINE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ENGINE)

import scripts.smoke as smoke
from engine.config import EngineConfig
from engine.cli import _build_engine_config_dict
from engine.lattice import LatticeIndex
from engine.question_pool import CsvQuestionPool
from engine.session import start_session, record_response, finalize_session, compute_verdicts
from engine.coverage import select_next_coverage
from engine.api.routes import _pick_question_and_stash, _stash_resolved
from engine.misconception import MISCONCEPTIONS

PROJECT = Path(os.environ.get("AML_DATA", os.path.join(os.path.dirname(os.path.abspath(__file__)), "data")))
LOOKUP = (Path(os.path.dirname(os.path.abspath(__file__))) / "inputs" / "tenant_question_lookup_v2.csv")
RETIRED = (Path(os.path.dirname(os.path.abspath(__file__))) / "inputs" / "retired_questions_v2.csv")
TENANT = "Delhi"
NODE_CEILING = 2_500_000   # safety: abort + report "exceeds ceiling" rather than hang

# ---- inputs ---------------------------------------------------------------
def load(reserve_by_grade=None):
    skills, priors, anchors, edges, qpath = smoke.step_1_load_data(PROJECT)
    cfg_dict = _build_engine_config_dict(skills=skills, anchors=anchors, priors=priors)
    # Shipped config: 25% reserves and conditional_extra = 0.
    reserve_by_grade = reserve_by_grade or {2: 7, 3: 11, 4: 15, 5: 19}
    cfg_dict["budgets"] = {g: {**b, "reserve_size": reserve_by_grade[g]}
                           for g, b in cfg_dict["budgets"].items()}
    cfg_dict["misconception"] = {"target": 2, "conditional_extra": 0,
                                 "clear_threshold": 0.75, "present_threshold": 0.50}
    cfg = EngineConfig.model_validate(cfg_dict)
    lattice = LatticeIndex(edges)
    pool = CsvQuestionPool(str(qpath), expected_skills={s["name"] for s in cfg_dict["skills"]},
                           selection="deterministic",
                           lookup_path=str(LOOKUP), retired_path=str(RETIRED),
                           misconception_target=cfg.misconception.target)
    fps = {"question_parameters": _fingerprint(qpath),
           "lattice": _fingerprint(PROJECT / "lattice_edges_final.xlsx"),
           "lookup": _fingerprint(LOOKUP), "retired": _fingerprint(RETIRED)}
    return cfg, lattice, pool, fps

def _fingerprint(path) -> str:
    h = hashlib.sha256(Path(path).read_bytes()).hexdigest()
    return f"sha256:{h[:16]}"

def _clone(s):
    """Fast session fork: shallow-copy the dataclass, then copy only the mutable
    containers record_response touches. ~30x faster than deepcopy (history entries
    are frozen and only appended, so sharing them is safe)."""
    c = copy.copy(s)
    c.posteriors = dict(s.posteriors)
    c.direct_obs_count = dict(s.direct_obs_count)
    c.questions_per_operation = dict(s.questions_per_operation)
    c.question_history = list(s.question_history)
    c.routing_mode_counts = dict(s.routing_mode_counts)
    c.propagation_updates_count = dict(s.propagation_updates_count)
    c.misconception_asked = dict(s.misconception_asked)
    c.misconception_correct = dict(s.misconception_correct)
    c.misconception_applicable = set(s.misconception_applicable)
    return c


# ---- state key (5.3) ------------------------------------------------------
def state_key(session, applicable, target, *, posterior_mode, params):
    """Single-pass key: bucketed posteriors + per-op counts + depth + phase +
    one below-target bit per applicable misconception + the pending question.
    Excludes the full (asked, correct) counts (those go in the leaf only).
    `posterior_mode` = "exact" | "zone" | "roundN"; the probe (probe_bucketing.py)
    shows zones are too coarse and 2 decimals is sound, so the build uses round3."""
    if posterior_mode == "exact":
        post = tuple(sorted((s, round(p, 9)) for s, p in session.posteriors.items()))
    elif posterior_mode == "zone":
        def zone(p):
            if p >= params.mastery_threshold: return 2
            if p <= params.not_mastered_threshold: return 0
            return 1
        post = tuple(sorted((s, zone(p)) for s, p in session.posteriors.items()))
    else:  # roundN
        nd = int(posterior_mode[5:])
        post = tuple(sorted((s, round(p, nd)) for s, p in session.posteriors.items()))
    per_op = tuple(sorted(session.questions_per_operation.items()))
    below = tuple(1 if session.misconception_asked.get(m, 0) < target else 0
                  for m in sorted(applicable))
    return (post, per_op, session.questions_total, session.reserve_phase_started_at,
            below, session.pending_question_id)

# ---- the walk (5.2) -------------------------------------------------------
class Builder:
    def __init__(self, cfg, lattice, pool, grade, posterior_mode="exact"):
        self.cfg, self.lattice, self.pool, self.grade = cfg, lattice, pool, grade
        self.posterior_mode = posterior_mode
        self.params = cfg.get_engine_params(grade, lattice)
        self.target = cfg.misconception.target
        self.applicable = pool.applicable_misconceptions(TENANT, grade, self.params.skills_in_scope)
        self.nodes_unused = None
        self.memo: Dict[bytes, bytes] = {}          # key-hash -> counts-hash
        self.manifest: set = set()
        self.leaf_count = 0
        self.merge_count = 0
        self.max_depth = 0
        self.count_divergences = 0
        self.aborted = False
        self.deadline = None

    def _counts(self, session):
        return (tuple(sorted(session.misconception_asked.items())),
                tuple(sorted(session.misconception_correct.items())))

    @staticmethod
    def _h(obj) -> bytes:
        return hashlib.blake2b(repr(obj).encode(), digest_size=12).digest()

    def _advance(self, session, is_correct):
        """Fork the session, apply one answer, return (child, finished)."""
        child = _clone(session)
        record_response(child, skill_id=child.pending_question_skill_id,
                        question_id=child.pending_question_id, is_correct=is_correct,
                        params=self.params, defer_next=True)
        nxt = select_next_coverage(child, self.params, self.pool)
        if nxt is None:
            finalize_session(child, self.params)
            return child, True
        sk, pick = nxt
        _stash_resolved(child, sk, pick)
        return child, False

    def walk(self, session, depth=0):
        """Memory-lean DAG walk: count distinct states (hashed single-pass key),
        leaves, merges; check leaf-count soundness; collect manifest. Does not
        retain node structures (that is checkpoint 2, gated on the count)."""
        if self.aborted:
            return
        if self.deadline and time.time() > self.deadline:
            self.aborted = True; return
        if len(self.memo) and len(self.memo) % 200000 == 0:
            print(f"    ...{len(self.memo):,} nodes  {time.time()-self._t0:.0f}s", flush=True)
        if session.pending_question_id is None:
            self.leaf_count += 1
            self.max_depth = max(self.max_depth, depth)
            return
        key = state_key(session, self.applicable, self.target,
                        posterior_mode=self.posterior_mode, params=self.params)
        kh = self._h(key)
        ch = self._h(self._counts(session))
        if kh in self.memo:
            self.merge_count += 1
            if self.memo[kh] != ch:                 # leaf-count soundness check
                self.count_divergences += 1
            return
        if len(self.memo) >= NODE_CEILING:
            self.aborted = True
            return
        self.memo[kh] = ch
        self.manifest.add(session.pending_question_id)
        c_sess, _ = self._advance(session, True)
        i_sess, _ = self._advance(session, False)
        self.walk(c_sess, depth + 1)
        self.walk(i_sess, depth + 1)

    def build(self, time_cap=None):
        self._t0 = time.time()
        if time_cap: self.deadline = self._t0 + time_cap
        sid = f"gen-{self.grade}"
        res = start_session(sub_session_id=sid, learner_id="g", tenant_id=TENANT,
                            class_id="c", grade=self.grade, engine_version="gen",
                            params=self.params)
        session = res.session
        session.misconception_applicable = self.applicable
        if res.first_question is not None:
            _pick_question_and_stash(res.first_question, session, self.pool,
                                     grade=self.grade, tenant_id=TENANT)
        self.walk(session)
        return self


if __name__ == "__main__":
    grade = int(sys.argv[1]) if len(sys.argv) > 1 else 2
    mode = sys.argv[2] if len(sys.argv) > 2 else "round3"
    cfg, lattice, pool, fps = load()
    t0 = time.time()
    b = Builder(cfg, lattice, pool, grade, posterior_mode=mode).build()
    dt = time.time() - t0
    n = len(b.memo)
    status = f"EXCEEDED CEILING ({NODE_CEILING:,})" if b.aborted else "complete"
    print(f"G{grade} mode={mode} budget={b.params.routing_config.total_budget} "
          f"reserve={b.params.reserve_size} applicable={len(b.applicable)}  [{status}]")
    print(f"  distinct single-pass nodes={n:,}  leaves(visited)={b.leaf_count:,}  "
          f"merges={b.merge_count:,}  max_depth={b.max_depth}")
    print(f"  manifest x_ids={len(b.manifest)}  build_time={dt:.1f}s")
    print(f"  MERGE SOUNDNESS: leaf-count divergences at merges={b.count_divergences} "
          f"({'SOUND' if b.count_divergences == 0 else 'UNSOUND - counts differ at merge'})")
